version: '3'
services:
#  kurate:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mariadb
#    ports:
#      - "8080:8080"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
